- hosts: all
  name: playbook to complete IDM configuration and installation
  remote_user: root
  vars_files:
    - vars.yml
  tasks:
    - name: import secret variable file
      include_vars: "vault"
      no_log: true

    - name: set hostname
      hostname:
        name: "{{ hostname_full }}"

    - name: add line to hosts file for self
      lineinfile:
        dest: /etc/hosts
        state: present
        regexp: "^{{ external_ip }}"
        line: "{{ external_ip }}  {{ hostname_full }}  {{ hostname_short }}"

    - name: test to see if selinux is running
      command: getenforce
      register: sestatus
      changed_when: false

    - name: register System with RHN Subscription Manager
      redhat_subscription:
        state: present
        username: "{{ rhn_user }}"
        password: "{{ rhn_pwd }}"
        pool: "{{ rhn_pool_name }}"
      when: ansible_distribution == 'RedHat' and register_rhn

    - name: disable all repositories
      command: subscription-manager repos --disable=\*
      when: ansible_distribution == 'RedHat' and register_rhn

    - name: enable the needed rhel repositories
      command: subscription-manager repos --enable={{ item }}
      with_items:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
      when: ansible_distribution == 'RedHat' and register_rhn

    - name: update packages
      yum:
        name: '*'
        state: latest
      register: yum_result
      async: 1000
      poll: 30

    - name: check Kernel is the Latest
      shell: if [ $(uname -r) == $(rpm -q kernel | tail -n 1 | sed -e 's/kernel-//g') ] ; then echo no ; else echo reboot; fi
      ignore_errors: true
      register: reboot_hint

    - name: make sure cloud-init is not installed
      yum:
        name: cloud-init
        state: absent

    - name: restart server to get updated kernel
      shell: sleep 2 && shutdown -r now "Ansible Restart Triggered for Undercloud Install"
      async: 1
      poll: 0
      ignore_errors: true
      when: yum_result.changed or reboot_hint.stdout.find("reboot") != -1

    - name: waiting for server to come back
      wait_for:
        host: "{{ inventory_hostname }}"
        state: started
        delay: 10
        connect_timeout: 5
        timeout: 300
        port: 22
      delegate_to: 127.0.0.1
      become: false
      ignore_errors: true

    - name: install IPA packages
      yum: 
        name: '{{ item }}'
        state: latest
      with_items:
        - ipa-server
        - ipa-server-dns

    - name: Setup IPA Server 
      command: ipa-server-install -Uq -r '{{ realm }}' -n '{{ domain }}' --allow-zone-overlap -p '{{ dm_pass }}' -a '{{ admin_pass }}' --setup-dns --forwarder '{{ forward_ip }}'
